# #Connecting Docker and PgAdmin (Week 1)
# services:
#   pgdatabase:
#     image: postgres:13
#     environment:
#       - POSTGRES_USER=root
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_DB=ny_taxi
#     volumes:
#       #NB local filepath is used so that our db is persisted  on every docker run
#       - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
#     ports:
#       - "5431:5432"
#   pgadmin:
#     image: dpage/pgadmin4
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=emiwest@admin.com
#       - PGADMIN_DEFAULT_PASSWORD=password
#     ports:
#       - "8080:80"
#_______________________________________________________________________________________________________________________
#Connecting Docker and Airflow (Week 2)
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ny_taxi
    volumes:
      #NB local filepath is used so that our db is persisted  on every docker run
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5431:5432"
    networks:
      - airflow      
  
networks:
  airflow:
    external:
      name: airflow_default